name: xvec_dev
channels:
  - conda-forge
  - conda-forge/label/shapely_dev
dependencies:
  - python
  # required
  - shapely=2
  - xarray
  # testing
  - pytest
  - pytest-cov
  - pytest-xdist
  # documentation
  - sphinx
  - myst-nb
  - sphinx-copybutton
  - numpydoc
  - pydata-sphinx-theme
  - geopandas
  # linting
  - flake8
  - black
  - isort
  - pip
  - pip:
      - sphinx_autosummary_accessors
